### ISSUE TITLE
Pg history viewer fails if logged action table has moved

### ISSUE THREAD

**Issue by haubourg** [qwat/pg-history-viewer#2]
```
ProgrammingError: relation "api_maj.logged_actions" does not exist LINE 1: ..., application_name, row_data, changed_fields FROM api_maj.lo...                                                             ^ 
Traceback (most recent call last):
  File "/home/regis/OSLANDIA/projets_locaux/TIGRE_STEA/GITLAB_specifique_qgis/1507_05_stea_tigre7/qgis/dot_qgis2/python/plugins/pg-history-viewer/main.py", line 108, in onListEvents
    selected_feature_id = feature_id)
  File "/home/regis/OSLANDIA/projets_locaux/TIGRE_STEA/GITLAB_specifique_qgis/1507_05_stea_tigre7/qgis/dot_qgis2/python/plugins/pg-history-viewer/event_dialog.py", line 207, in __init__
    self.populate()
  File "/home/regis/OSLANDIA/projets_locaux/TIGRE_STEA/GITLAB_specifique_qgis/1507_05_stea_tigre7/qgis/dot_qgis2/python/plugins/pg-history-viewer/event_dialog.py", line 306, in populate
    cur.execute(q)
ProgrammingError: relation "api_maj.logged_actions" does not exist
LINE 1: ..., application_name, row_data, changed_fields FROM api_maj.lo...
                                                             
```
and worse, then if trying to open configuration to change it, QGIS crashes

**Comment by haubourg** [comment]
Only way to have it back is to edit manually the qgs file. 
IMHO, if the audit table or replay functions are not found, it should except the error and open the configuration window so that the user can fix that

**Comment by lbartoletti** [comment]
https://github.com/qwat/pg-history-viewer/pull/15
